import { Hono } from "hono";
import { adminAuthMiddleware } from "../../middleware/admin-auth-middleware";
import { adminLimiterMiddleware } from "../../middleware/rate-limiter";
import { employeeRouter } from "./employee-router";
import { adminUserRouter } from "./admin-user-router";
import { apiClientRouter } from "./api-client-router";
import { workingDayRouter } from "./working-day-router";
import { academicYearRouter } from "./academic-year-router";
import { classRouter } from "./class-router";
import { unitRouter } from "./unit-router";
import { jobPositionRouter } from "./job-position-router";
import { jobLevelRouter } from "./job-level-router";
import { buildingRouter } from "./building-router";
import { pcActivityMasterRouter } from "./pc-activity-master-router";
import { gradeRouter } from "./grade-router";
import { studentRouter } from "./student-router";
import { enrollmentRouter } from "./enrollment-router";
import { auditLogRouter } from "./audit-log-router";
import { studentSupportAssignmentRouter } from "./student-support-assignment-router";

export const adminRouter = new Hono();

adminRouter.use("*", adminLimiterMiddleware);
adminRouter.use("*", adminAuthMiddleware);

adminRouter.route("/employees", employeeRouter);
adminRouter.route("/admin-users", adminUserRouter);
adminRouter.route("/api-clients", apiClientRouter);
adminRouter.route("/working-days", workingDayRouter);
adminRouter.route("/academic-years", academicYearRouter);
adminRouter.route("/classes", classRouter);
adminRouter.route("/units", unitRouter);
adminRouter.route("/job-positions", jobPositionRouter);
adminRouter.route("/job-levels", jobLevelRouter);
adminRouter.route("/buildings", buildingRouter);
adminRouter.route("/pc-activities-master", pcActivityMasterRouter);
adminRouter.route("/grades", gradeRouter);
adminRouter.route("/students", studentRouter);
adminRouter.route("/enrollments", enrollmentRouter);
adminRouter.route("/audit-logs", auditLogRouter);
adminRouter.route("/support-assignments", studentSupportAssignmentRouter);
