ALTER TYPE "AuditAction" ADD VALUE 'REQUEST_IDENTIFIER_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'APPROVE_IDENTIFIER_CHANGE_REQUEST';
ALTER TYPE "AuditAction" ADD VALUE 'REJECT_IDENTIFIER_CHANGE_REQUEST';
