-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'APPLICATION_RETIRE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'APPLICATION_RESTORE';

-- AlterTable
ALTER TABLE "applications" ADD COLUMN "retired_at" TIMESTAMP(3);
