// Keeps the icon list of Application Access in step with the Hub.
//
//   bun run sync:hub-icons    rewrites the two generated files from the Hub
//   bun run check:hub-icons   only compares, fails when they differ
//
// The Hub repo is read from HUB_REPO_PATH (default ../../mws-hub, next to this one).
import { existsSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const SOURCE = "frontend/src/data/hubCategories.ts";
const SERVER_FILE = resolve(import.meta.dir, "../src/constants/hub-icons.ts");
const CLIENT_FILE = resolve(import.meta.dir, "../../client/src/features/application-access/utils/hubIcons.js");

// The names inside `export const HUB_ICONS = { ... }` of the Hub.
export function parseHubIconNames(source: string): string[] {
  const start = source.indexOf("export const HUB_ICONS");
  if (start === -1) throw new Error("HUB_ICONS was not found in the Hub file");
  const body = source.slice(source.indexOf("{", start) + 1, source.indexOf("\n};", start));
  const names = [...body.matchAll(/^\s{2}([A-Za-z0-9]+),?\s*$/gm)].map((match) => match[1]!);
  if (names.length === 0) throw new Error("No icons were found in HUB_ICONS");
  if (new Set(names).size !== names.length) throw new Error("HUB_ICONS has a name twice");
  return names;
}

const note = `The icons the Hub can draw on an application card. Same names as HUB_ICONS in
mws-hub/${SOURCE}. A name outside this list falls back to AppWindow in the Hub.
Generated by server/scripts/sync-hub-icons.ts, run \`bun run sync:hub-icons\` after the Hub changes its icons.`;

export function renderServerFile(names: string[]): string {
  const comment = note.split("\n").map((line) => `// ${line}`).join("\n");
  return `${comment}
export const HUB_ICON_NAMES = [
${names.map((name) => `  "${name}"`).join(",\n")},
] as const;

const KNOWN = new Set<string>(HUB_ICON_NAMES);

export const isHubIcon = (name: string): boolean => KNOWN.has(name);
`;
}

export function renderClientFile(names: string[]): string {
  const comment = note.split("\n").map((line) => `// ${line}`).join("\n");
  const list = names.map((name) => `  ${name}`).join(",\n");
  return `import {
${list},
} from 'lucide-react'

${comment}
export const HUB_ICONS = {
${list},
}

export const HUB_ICON_NAMES = Object.keys(HUB_ICONS)

export const DEFAULT_ICON = 'AppWindow'
`;
}

function hubFile(): string {
  const repo = resolve(import.meta.dir, "..", process.env.HUB_REPO_PATH ?? "../../mws-hub");
  const file = resolve(repo, SOURCE);
  if (!existsSync(file)) throw new Error(`The Hub repo was not found at ${repo}. Set HUB_REPO_PATH.`);
  return readFileSync(file, "utf8");
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const names = parseHubIconNames(hubFile());
  const targets = [
    { file: SERVER_FILE, text: renderServerFile(names) },
    { file: CLIENT_FILE, text: renderClientFile(names) },
  ];
  const stale = targets.filter((target) => !existsSync(target.file) || readFileSync(target.file, "utf8") !== target.text);
  if (check) {
    if (stale.length > 0) {
      console.error(`The icon list is out of step with the Hub (${names.length} icons there). Run: bun run sync:hub-icons`);
      for (const target of stale) console.error(`  ${target.file}`);
      process.exit(1);
    }
    console.log(`Icon list matches the Hub (${names.length} icons).`);
  } else {
    for (const target of stale) writeFileSync(target.file, target.text);
    console.log(stale.length ? `Updated ${stale.length} file(s) from ${names.length} Hub icons.` : "Already in step with the Hub.");
  }
}
